#!/bin/bash

# 定义基础目录
base_dir="go-learning"

# 创建基础目录
mkdir -p $base_dir

# 创建README.md和.gitignore文件
touch $base_dir/README.md
touch $base_dir/.gitignore

# 定义学习计划及知识内容的目录结构
topics=(
    "01_基础之变量和常量"
    "02_基础之基本数据类型"
    "03_基础之运算符"
    "04_基础之流程控制"
    "05_基础之数组"
    "06_基础之切片"
    "07_基础之map"
    "08_基础之函数/函数部分"
    "09_基础之函数/匿名函数和闭包部分"
    "10_基础之指针"
    "11_基础之结构体/01_自定义类型和类型别名"
    "11_基础之结构体/02_结构体定义与实例化"
    "11_基础之结构体/03_方法和接收者"
    "11_基础之结构体/04_结构体嵌套"
    "11_基础之结构体/05_结构体字段可见性和JSON"
    "11_基础之结构体/06_学员信息管理系统练习"
    "12_基础之包"
    "13_基础之接口"
    "14_基础之error接口"
    "15_基础之反射/01_反射初识"
    "15_基础之反射/02_结构体反射"
    "16_基础之并发/01_goroutine"
    "16_基础之并发/02_channel"
    "16_基础之并发/03_并发同步和锁"
    "17_基础之处理并发错误"
    "18_基础之网络编程"
    "19_基础之单元测试"
    "20_泛型"
    "21_何时使用泛型"
    "22_常用标准库/01_fmt与格式化占位符"
    "22_常用标准库/02_time"
    "22_常用标准库/03_flag"
    "22_常用标准库/04_log"
    "22_常用标准库/05_文件操作"
    "22_常用标准库/06_strconv"
    "22_常用标准库/07_net_http"
    "22_常用标准库/08_context"
    "23_单元测试教程/01_单元测试基础"
    "23_单元测试教程/02_网络测试"
    "23_单元测试教程/03_MySQL和Redis测试"
    "23_单元测试教程/04_mock接口测试"
    "23_单元测试教程/05_monkey打桩测试"
    "23_单元测试教程/06_goconvey的使用"
    "23_单元测试教程/07_编写可测试的代码"
    "24_数据库相关/01_Go操作MySQL——database_sql使用指南"
    "24_数据库相关/02_更强大、更好用的sqlx库使用指南"
    "24_数据库相关/03_sqlx库批量插入数据"
    "24_数据库相关/04_Go操作Redis——go-redis库使用指南"
    "24_数据库相关/05_Go操作MongoDB"
    "24_数据库相关/06_Canal介绍和使用指南"
    "25_Web开发相关/01_template"
    "25_Web开发相关/02_01——template模板初识"
    "25_Web开发相关/02_02——模板语法详解"
    "25_Web开发相关/02_03——模板嵌套"
    "25_Web开发相关/02_04——模板继承"
    "25_Web开发相关/02_05——模板补充"
    "25_Web开发相关/03_gin框架快速指南"
    "25_Web开发相关/03_gin框架web实战视频教程"
    "25_Web开发相关/03_gin框架路由拆分与注册"
    "25_Web开发相关/04_在gin框架中使用JWT认证"
    "25_Web开发相关/05_使用Air实现Go程序实时热重载"
    "25_Web开发相关/06_优雅的关机或重启gin项目"
    "25_Web开发相关/07_如何使用docker部署Go Web程序"
    "25_Web开发相关/08_Cookie和Session"
    "25_Web开发相关/09_gin框架中使用zap日志库"
    "25_Web开发相关/10_gin框架源码解析"
    "25_Web开发相关/11_gin框架中使用validator若干实用技巧"
    "25_Web开发相关/12_使用swagger生成接口文档"
    "25_Web开发相关/13_HTTP Server常用压测工具介绍"
    "25_Web开发相关/14_漏桶和令牌桶限流策略介绍及使用"
    "25_Web开发相关/15_部署Go语言程序的N种方法"
    "26_微服务相关/01_RPC的原理与Go RPC"
    "26_微服务相关/02_protobuf v3语法中文指南"
    "26_微服务相关/03_Go语言protobuf使用指南"
    "26_微服务相关/04_protobuf中oneof、WrapValue和FieldMask的使用"
    "26_微服务相关/05_gRPC教程"
    "26_微服务相关/06_gRPC中的名称解析和负载均衡"
    "26_微服务相关/07_gRPC-Gateway教程"
    "26_微服务相关/08_gRPC-Transcoding"
    "26_微服务相关/09_consul服务注册与发现"
    "26_微服务相关/10_Apollo配置中心"
    "27_Go-kit/01_基础示例"
    "27_Go-kit/02_gRPC"
    "27_Go-kit/03_项目目录结构"
    "27_Go-kit/04_中间件"
    "27_Go-kit/05_调用其他服务"
    "27_Go-kit/06_服务发现与负载均衡"
    "28_常用组件和技巧/01_你需要知道的那些go语言json技巧"
    "28_常用组件和技巧/02_option选项模式"
    "28_常用组件和技巧/03_Go语言中的单例模式（翻译）"
    "28_常用组件和技巧/04_结构体转map的若干方法"
    "28_常用组件和技巧/05_Go语言配置管理神器——Viper中文教程"
    "28_常用组件和技巧/06_Go操作NSQ"
    "28_常用组件和技巧/07_Go操作kafka之sarama"
    "28_常用组件和技巧/08_Go操作Kafka之kafka-go"
    "28_常用组件和技巧/09_Go操作etcd"
    "28_常用组件和技巧/10_Go语言获取系统性能数据gopsutil库"
    "28_常用组件和技巧/11_二进制协议gob及msgpack介绍"
    "28_常用组件和技巧/12_influxDB"
    "28_常用组件和技巧/13_Elasticsearch简明指南"
    "28_常用组件和技巧/14_go-elasticsearch使用指南"
    "28_常用组件和技巧/15_Go第三方日志库logrus"
    "28_常用组件和技巧/16_Go语言项目中使用zap日志库（翻译）"
    "28_常用组件和技巧/17_Go pprof性能调优"
    "28_常用组件和技巧/18_为Go项目编写Makefile"
    "28_常用组件和技巧/19_在select语句中实现优先级"
)


# 创建目录及文件，并生成README.md模板
for topic in "${topics[@]}"; do
    # 替换目录名中的空格为下划线
    dir=$(echo "$topic" | sed 's/ /_/g')
    # 创建目录
    mkdir -p "$base_dir/$dir"
    # 创建main.go或main_test.go文件
    if [[ "$dir" == *"_单元测试"* || "$dir" == *"_测试"* ]]; then
        touch "$base_dir/$dir/main_test.go"
    else
        touch "$base_dir/$dir/main.go"
    fi
    # 创建README.md文件并写入模板内容
    readme_file="$base_dir/$dir/README.md"
    touch "$readme_file"
    echo "# $topic" > "$readme_file"
    echo "" >> "$readme_file"
    echo "## 介绍" >> "$readme_file"
    echo "该部分主要介绍$topic的相关内容。" >> "$readme_file"
    echo "" >> "$readme_file"
    echo "## 内容" >> "$readme_file"
    echo "- 相关概念" >> "$readme_file"
    echo "- 使用示例" >> "$readme_file"
    echo "- 注意事项" >> "$readme_file"
    echo "" >> "$readme_file"
    echo "## 示例代码" >> "$readme_file"
    echo "\`\`\`go" >> "$readme_file"
    echo "// 示例代码放在这里" >> "$readme_file"
    echo "\`\`\`" >> "$readme_file"
done

echo "目录结构和文件已创建完成！"

